### ISSUE TITLE
мне как то нужно отображать фио преподов

### ISSUE THREAD

**Issue by Vatgernn** [MalyshM/vkr#108]
![image](https://github.com/MalyshM/vkr/assets/116349791/e7bfbf02-47d9-4e27-919d-9428ada39367)

в селекте с преподом мы выбираем преподов (строки)

передаем в запрос массив строк 

получаем в ответе teacher_id (в объектах массива) 

и соответсвенно я отображаю этот айди 

в идеале надо фио отображать 

есть идеи как несложно это сделать ?

ты сам вряд ли мне будешь фио возврщать (хз спрашивал ли ты об этом)

или другой варик мне ещё один роут запускать который будет выдавать преподов - их фио и айди 
потом как то сверять на моменте показа айди выбранного и того что в пришло по запросу и отображать уже фио ?

звучит как ебанутейший костыль 

роут **stud_scatter_plot**

**Comment by MalyshM** [comment]
@Vatgernn сделал, теперь везде team_id = название команды, а teacher_ID = имя преподавателя
