### ISSUE TITLE
добавить каунтер занятий

### ISSUE THREAD

**Issue by MalyshM** [MalyshM/vkr#114]
в scatter плоты

**Comment by MalyshM** [comment]
@Vatgernn добавил во все роуты для стр scatter plot

**Comment by Vatgernn** [comment]
@MalyshM 
каунтер очень костыльно получается
как видишь на скрине создаются новые объекты - и за свёт имеющихся значений lesson_counter - отображается сверху 
фигня 
![image](https://github.com/MalyshM/vkr/assets/116349791/c9ab08c7-504a-4436-9af0-3154cfcd2749)

предлагаю посещаемость сделать из оси х в y (потому что в плотли js есть такая тема - двойная ось для y - для х нету - ток костыльно)
и тем самым будет:

посещаемость и каунтер по y 
успеваемость по x

**Comment by Vatgernn** [comment]
@MalyshM 
что то в целом окей получается 
но не оч 
надо чтоб ты глянул и сказал так ли будет

**Comment by Vatgernn** [comment]
2 варика есть: 
когда передаёшь одно значение:
![image](https://github.com/MalyshM/vkr/assets/116349791/95337c60-5451-4a13-9467-9812ea059462)
то оно встаёт якобы по середине и туда сюда скролится
![image](https://github.com/MalyshM/vkr/assets/116349791/a4191d18-e530-4525-96dc-8e93a114de4d)

если будешь передавать 2 значения в массиве:
![image](https://github.com/MalyshM/vkr/assets/116349791/8de0e5a6-ee74-486c-8233-2bca14acd6ba)
то появляется черная линия снизу - типа ноль
![image](https://github.com/MalyshM/vkr/assets/116349791/5249c0df-d129-4048-982c-e9e9a409f377)
