### ISSUE TITLE
исправить баг для /api/kr_analyse_with_filters

### ISSUE THREAD

**Issue by Vatgernn** [MalyshM/vkr#121]
для параметров speciality и teacher - не работает фио преподов и название специальностей 
приходит 500 ошибка в свагере

_"t.id IN (Трефилин Иван Андреевич)"_

![image](https://github.com/MalyshM/vkr/assets/116349791/c8cff6b3-5b6e-4795-afb7-048b04804b46)

![image](https://github.com/MalyshM/vkr/assets/116349791/c429acb0-567a-43d3-921d-e6c2fd5d73bb)

**Comment by Vatgernn** [comment]
@MalyshM 
напиши потом сюда какие параметры какие данные ожидают 
пока ожидаю также как и в scatter plot:

токен - строка
режим - int (0 1 2)
кр - строка
препод - массив фио
команда -массив id
специальности - массив speciality

**Comment by Vatgernn** [comment]
@MalyshM 
1. в запросе "кр с фильтрами" - препод ожидается в виде айди как ты и сказал 
2.  но в запросе "выдать группы по выбранным преподам" - там ожидается фио 

![image](https://github.com/MalyshM/vkr/assets/116349791/ed5083c2-e0c8-4e27-8b10-952e6f031b5f)
![image](https://github.com/MalyshM/vkr/assets/116349791/779fd870-5867-44e7-bc54-a6718a7c8e80)

**Comment by MalyshM** [comment]
"в запросе "кр с фильтрами" - препод ожидается в виде айди как ты и сказал
но в запросе "выдать группы по выбранным преподам" - там ожидается фио"
сделал логику фулл такую же, как в scatter plot
@Vatgernn

**Comment by Vatgernn** [comment]
@MalyshM 
"в запросе "кр с фильтрами" - специальность что ожидает, подскажи пж 
в свагере 500 выдаёт 
![image](https://github.com/MalyshM/vkr/assets/116349791/b33fd2c3-4d21-4ca0-8e62-b2f67fcd00fd)
