### ISSUE TITLE
в момент передачи студентов переносить и группу в которой находятся 

### ISSUE THREAD

**Issue by Vatgernn** [MalyshM/vkr#129]
могу пожелание насчет 3 пункта написать ?
можно в момент передачи мне студентов — переносить также и группу (либо id либо name - нужно будет их как то перекидывать на главную стр) в которой находятся студенты 

знаю что так и планировал 
просто вот делаю шаблоны и задумался об этом 

щас скажешь: "здравый, тише-тише"

**Comment by MalyshM** [comment]
в какие роуты это добавить? скинь список, пожалуйста @Vatgernn

**Comment by MalyshM** [comment]
я сделал на стр топов это, а где еще надо не знаю

**Comment by MalyshM** [comment]
в какие роуты это добавить? скинь список, пожалуйста @Vatgernn
я сделал на стр топов это, а где еще надо не знаю

**Comment by Vatgernn** [comment]
@MalyshM 
всё также на **стр топов** - но можно теперь при следующих параметрах:
![image](https://github.com/MalyshM/vkr/assets/116349791/76e85f01-edd9-4740-b7ee-1e67939cd511)

то есть когда режим (2) препода выбираем - то видим его студентов - хочу прикрутить из какой он группы

**Comment by MalyshM** [comment]
нет, не буду прикручивать, в личке написал почему @Vatgernn 

если это все, то можешь закрыть

**Comment by Vatgernn** [comment]
а для /api/lagging_students можно ли отправлять teacher_name если type_group_by = 0 ?

**Comment by Vatgernn** [comment]
@MalyshM 

а для /api/lagging_students можно ли отправлять teacher_name если type_group_by = 0 ?
