### ISSUE TITLE
топ сильных слабых команд и студентов

### ISSUE THREAD

**Issue by MalyshM** [MalyshM/vkr#132]
можно подумать над общей стр для кураторов, где мы выделяем топ 10 сильных и слабых команд просто чтобы сразу знать что смотреть, то же самое со студентами. Когда кликаешь на команду - переходишь на нашу главную стр с этой выбранной командой. Думаю преподы тоже могут видеть эту стр, но со своими командами

**Comment by MalyshM** [comment]
сделал, понять что как работает сложно, если не получится понять, спрашивай у меня

@Vatgernn

**Comment by MalyshM** [comment]
добавить роут с топ 10 команд по медиане на основе имеющегося

**Comment by Vatgernn** [comment]
@MalyshM 
топ 10 лучших худших сделал

**Comment by MalyshM** [comment]
@Vatgernn сделал

**Comment by MalyshM** [comment]
переименовать на топ 10 учеников (подумать над неймингом)

**Comment by Vatgernn** [comment]
топ 10 команд сделал
