### ISSUE TITLE
стр для неуспевающих студентов

### ISSUE THREAD

**Issue by MalyshM** [MalyshM/vkr#133]
Сделать стр именно для неуспевающих студентов, где будет их динамическая посещаемость и успеваемость от худшего к лучшему с порогом прям в роуте, что препод напишет 20, и покажут всех студентов его команд, у которого на текущий момент меньше либо равно 20 баллов. Будет кнопка "выгрузить студентов" и "массовая рассылка этой группе студентов"

сюда еще надо добавить bool на то, по баллам или по посещаемости это все выдается 

еще оно должно работать со всей гибкой настройкой

**Comment by MalyshM** [comment]
@Vatgernn  сделал, теперь можешь реализовывать

**Comment by Vatgernn** [comment]
отдельная

**Comment by Vatgernn** [comment]
сделал
Миша говорит что хочет чтобы при нажатии открывалось - но как то не здраво
