### ISSUE TITLE
/api/attendance_num_for_stud_for_team

### ISSUE THREAD

**Issue by Vatgernn** [MalyshM/vkr#51]
в запросе /api/attendance_num_for_stud_for_team
id_team = 12 (это группа 09.04) 

на первой учебной встрече всего 1 чел был - по крайней меер так отметили 
![1111](https://github.com/MalyshM/vkr/assets/116349791/cefc5f21-fe62-4e5b-80a4-c212d54afc9f)

**Comment by Vatgernn** [comment]
типа это так и должно быть 
или косячок на бэке есть ?

**Comment by MalyshM** [comment]
починил, ошибка была в ETL, надо теперь заново своих юзеров сделать(я своих сам сделаю по типу string и Павлова Елена Александровна

**Comment by MalyshM** [comment]
починил, ошибка была в ETL, надо теперь заново своих юзеров сделать(я своих сам сделаю по типу string и Павлова Елена Александровна
