### ISSUE TITLE
kr_page

### ISSUE THREAD

**Issue by MalyshM** [MalyshM/vkr#67]
вот в этом селекте должны быть команды выбранного слева преподавателя, если он выбран или все доступные юзеру команды, если преподаватель не выбран
![DwvVPIdxFFo](https://github.com/MalyshM/vkr/assets/112288146/22a58650-e904-41c9-880c-a710a6b76252)

**Comment by MalyshM** [comment]
@Vatgernn

**Comment by Vatgernn** [comment]
@MalyshM так у нас учебные группы отображаются по токену - когда препод входит 
тут нужен отдельный роут - чтоб по ФИО препода или его id - доставать прикрепленные к нему группы
или я чего то не понимаю

**Comment by MalyshM** [comment]
согласен, для этого я сделаю отдельный роут с нуллаблом выбора определенных преподов, если нет выбора преподов - то преподы по токену, иначе по массиву преподов, у меня где-то это уже реализовано, так что завтра сделаю фастом

**Comment by MalyshM** [comment]
сделал @Vatgernn

**Comment by Vatgernn** [comment]
@MalyshM 
как называется роут с выдачей учебных групп по фио препода ?
я нашел только /api/get_all_specialities_by_teacher_arr - тут выдача направлений под препода

**Comment by MalyshM** [comment]
добавил, прости, перепутал роуты
 @Vatgernn 
 /get_teams_for_param_without_lect

**Comment by Vatgernn** [comment]
1 дописать запросы
2 юс эфект и в нем фэтч
3 в селекте проверка

**Comment by Vatgernn** [comment]
мультивыбор и гибкие настройки есть 
кроме того что сам запрос не отправляется 
@MalyshM
