### ISSUE TITLE
ваши команды

### ISSUE THREAD

**Issue by MalyshM** [MalyshM/vkr#68]
![image](https://github.com/MalyshM/vkr/assets/112288146/30b92d1a-4c6b-490f-bb4f-37508b8696ca)

когда выбираешь группировку по преподу график не строится

**Comment by Vatgernn** [comment]
на проде старая версия 
у себя я уже пофиксил
![image](https://github.com/MalyshM/vkr/assets/116349791/b68e2eac-bdf4-428c-8b67-25c600139bbe)
