### ISSUE TITLE
ваши команды

### ISSUE THREAD

**Issue by MalyshM** [MalyshM/vkr#69]
![image](https://github.com/MalyshM/vkr/assets/112288146/f872c8cf-ce9d-41a4-8dea-837b258d581f)

есть группирвока преподов по цветам, но в легенде цвета одинаковые

**Comment by Vatgernn** [comment]
@MalyshM 
а как ты хочешь - чтоб была легенда или нет ? - залитая на прод ломанная - там надо подумать как грамотно передавать

**Comment by MalyshM** [comment]
она нужна обязательно. ты можешь в теории сделать при определении цвета уникального ключа добавлять этот цвет и сам ключ снизу в легенду

**Comment by Vatgernn** [comment]
сделал
