### ISSUE TITLE
сделай лейбл for mochael

### ISSUE THREAD

**Issue by Vatgernn** [MalyshM/vkr#77]
начальник, хочу шоб для роута "/api/speciality_kr_total_points_attendance_dynamic" - в параметрах добавить выбор направления "моаис", "матан" - поле необязательное 

![image](https://github.com/MalyshM/vkr/assets/116349791/49f981c7-b9d4-4945-936c-6888021cf24c)

**Comment by MalyshM** [comment]
добавил роут get_all_specialities_by_teacher_arr, и обновил роут speciality_kr_total_points_attendance_dynamic и все похожие для этой страницы.
Получаешь список доступных специальностей на основе get_all_specialities_by_teacher_arr, туда отправляешь строку препод,препод и показываешь ответ юзеру в селекте
@Vatgernn
