### ISSUE TITLE
График рассеивания

### ISSUE THREAD

**Issue by MalyshM** [MalyshM/vkr#88]
График рассеивания необходим.
Маршрут с 3 типами разрезов - преподаватели, направления, команды
Можно выбирать пулл преподавателей и направлений, если выбран разрез преподов, то показывать только доступные направления выбранных преподов
если выбран разрез направлений, то показывать только доступных преподавателей по выбранным направлениям
если выбран разрез по командам, то оба условия работают

грубо говоря, будет как на стр кр с фильтрами.

ответом будет массив из 4 словарей, в каждом словаре будет разное количество полей в зависимости от выбранных параметров

добавить функцию n-диаграм рассеивания

пингануть Влада как сделаю

**Comment by MalyshM** [comment]
сделать доки

добавить функцию n-диаграм рассеивания

**Comment by MalyshM** [comment]
@Vatgernn stud_scatter_plot роут, 

еще раз функциональность на фронте

Можно выбирать пулл преподавателей и направлений, если выбран разрез преподов, то показывать только доступные направления выбранных преподов
если выбран разрез направлений, то показывать только доступных преподавателей по выбранным направлениям
если выбран разрез по командам, то оба условия работают

**Comment by Vatgernn** [comment]
@MalyshM 
я не нашел роутов для гибкой настройки фильтров
1. если выбран препод - то отображаются ток его специальности - такой есть - но сейчас для stud_scatter_plot не работают специальности 
2. если выбраны направления - то показывать преподов доступных - такого не нашел (если есть подскажи название)
3. если выбраны группы - то оба условия учитывать - тоже не нашел

**Comment by MalyshM** [comment]
![image](https://github.com/MalyshM/vkr/assets/112288146/a1e7965f-c3d4-47cd-87fe-6c30e446e19b)

команды и направления по преподавателям

добавлю потом еще преподаватели и команды по направлениям

**Comment by MalyshM** [comment]
![image](https://github.com@Vatgernn MalyshM/vkr/assets/112288146/a8cc0653-1dbd-46b5-9e2e-d5a1db8a7bd6)

@Vatgernn добавил все что хотел

**Comment by MalyshM** [comment]
![image](https://github.com/MalyshM/vkr/assets/112288146/86df239a-d2c0-4be1-8f89-9097ed5b8bc0)

**Comment by Vatgernn** [comment]
сделал
