### ISSUE TITLE
кластеризация на высоком уровне 

### ISSUE THREAD

**Issue by MalyshM** [MalyshM/vkr#90]
Второе кластеризация на высоком уровне 
Делаем определенную кластеризацию по командам по группам по специальностям.

по сути тот же график рассеивания, только вместо точек студентов, показываем точки успеваемости команд/направлений/преподавателей

если забыл как надо смотреть https://github.com/MalyshM/vkr/issues/88

**Comment by MalyshM** [comment]
сделал роут scatter_plot_by_section, @Vatgernn добавь его как роут снизу во вкладке графиков рассеивания
логика по сути одна и та же, только поля попроще(не массив иксов и игриков, а 1 х и 1 у

**Comment by Vatgernn** [comment]
сделал (насколько понимаю)
@MalyshM
